name: barcode_scanner_app
description: A Flutter app to scan food barcodes and show nutrition info.
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  google_mlkit_barcode_scanning: ^0.14.1
  http: ^1.2.1
  path_provider: ^2.1.1
  flutter_lints: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1  # <-- moved here correctly

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/liverlogo.png"
