name: liver_wise
description: A Flutter app to scan food barcodes and show nutrition info.
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3 
  logger: ^2.0.2
  image_picker: ^1.0.7
  google_mlkit_barcode_scanning: ^0.14.1
  http: ^1.2.1
  path_provider: ^2.1.1
  supabase_flutter: ^2.3.4
  google_mobile_ads: ^6.0.0
  in_app_purchase: ^3.1.13
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/background.png
    - assets/icon/liverlogo.png  # Add this since it's referenced in flutter_launcher_icons

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/liverlogo.png"